apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-agent-ingress
spec:
  rules:
    - host: enterprise-agent.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enterprise-api
                port:
                  number: 8100
